-- =====================================================================
-- VALIDATION SCRIPT: Verify all exercise objects are correctly built
-- Run this after completing all 3 modules.
-- Returns a result set with CHECK_NAME, STATUS (PASS/FAIL), and DETAIL.
-- =====================================================================

USE ROLE TB_DATA_ENGINEER;
USE WAREHOUSE TB_DE_WH;

-- =====================================================================
-- SECTION 1: Object Existence Checks
-- =====================================================================

SELECT 'STAGING_TABLE_EXISTS: STG_MENU' AS CHECK_NAME,
       IFF(COUNT(*) = 1, 'PASS', 'FAIL') AS STATUS,
       IFF(COUNT(*) = 1, 'Table exists', 'Table NOT found') AS DETAIL
FROM TASTYBYTES_REFINED.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'STAGING' AND TABLE_NAME = 'STG_MENU'

UNION ALL
SELECT 'STAGING_TABLE_EXISTS: STG_ORDER_HEADER',
       IFF(COUNT(*) = 1, 'PASS', 'FAIL'),
       IFF(COUNT(*) = 1, 'Table exists', 'Table NOT found')
FROM TASTYBYTES_REFINED.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'STAGING' AND TABLE_NAME = 'STG_ORDER_HEADER'

UNION ALL
SELECT 'STAGING_TABLE_EXISTS: STG_ORDER_DETAIL',
       IFF(COUNT(*) = 1, 'PASS', 'FAIL'),
       IFF(COUNT(*) = 1, 'Table exists', 'Table NOT found')
FROM TASTYBYTES_REFINED.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'STAGING' AND TABLE_NAME = 'STG_ORDER_DETAIL'

UNION ALL
SELECT 'STAGING_TABLE_EXISTS: STG_CUSTOMER_LOYALTY',
       IFF(COUNT(*) = 1, 'PASS', 'FAIL'),
       IFF(COUNT(*) = 1, 'Table exists', 'Table NOT found')
FROM TASTYBYTES_REFINED.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'STAGING' AND TABLE_NAME = 'STG_CUSTOMER_LOYALTY'

UNION ALL
SELECT 'WAREHOUSE_TABLE_EXISTS: DIM_MENU',
       IFF(COUNT(*) = 1, 'PASS', 'FAIL'),
       IFF(COUNT(*) = 1, 'Table exists', 'Table NOT found')
FROM TASTYBYTES_CONSUMPTION.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'WAREHOUSE' AND TABLE_NAME = 'DIM_MENU'

UNION ALL
SELECT 'WAREHOUSE_TABLE_EXISTS: DIM_CUSTOMER',
       IFF(COUNT(*) = 1, 'PASS', 'FAIL'),
       IFF(COUNT(*) = 1, 'Table exists', 'Table NOT found')
FROM TASTYBYTES_CONSUMPTION.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'WAREHOUSE' AND TABLE_NAME = 'DIM_CUSTOMER'

UNION ALL
SELECT 'WAREHOUSE_TABLE_EXISTS: FACT_ORDER_LINE',
       IFF(COUNT(*) = 1, 'PASS', 'FAIL'),
       IFF(COUNT(*) = 1, 'Table exists', 'Table NOT found')
FROM TASTYBYTES_CONSUMPTION.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'WAREHOUSE' AND TABLE_NAME = 'FACT_ORDER_LINE'

UNION ALL
SELECT 'VIEW_EXISTS: RPT_MONTHLY_MENU_SALES',
       IFF(COUNT(*) = 1, 'PASS', 'FAIL'),
       IFF(COUNT(*) = 1, 'View exists', 'View NOT found')
FROM TASTYBYTES_CONSUMPTION.INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'ANALYTICS' AND TABLE_NAME = 'RPT_MONTHLY_MENU_SALES'

-- =====================================================================
-- SECTION 2: Schema / Column Checks
-- =====================================================================

UNION ALL
SELECT 'SCHEMA_CHECK: STG_ORDER_HEADER.LOCATION_ID is NUMBER',
       IFF(DATA_TYPE = 'NUMBER', 'PASS', 'FAIL'),
       'Data type is: ' || DATA_TYPE
FROM TASTYBYTES_REFINED.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'STAGING' AND TABLE_NAME = 'STG_ORDER_HEADER' AND COLUMN_NAME = 'LOCATION_ID'

UNION ALL
SELECT 'SCHEMA_CHECK: STG_ORDER_HEADER.SERVED_TS is TIMESTAMP',
       IFF(DATA_TYPE LIKE 'TIMESTAMP%', 'PASS', 'FAIL'),
       'Data type is: ' || DATA_TYPE
FROM TASTYBYTES_REFINED.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'STAGING' AND TABLE_NAME = 'STG_ORDER_HEADER' AND COLUMN_NAME = 'SERVED_TS'

UNION ALL
SELECT 'SCHEMA_CHECK: STG_ORDER_HEADER.ORDER_TAX_AMOUNT is NUMBER',
       IFF(DATA_TYPE = 'NUMBER', 'PASS', 'FAIL'),
       'Data type is: ' || DATA_TYPE
FROM TASTYBYTES_REFINED.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'STAGING' AND TABLE_NAME = 'STG_ORDER_HEADER' AND COLUMN_NAME = 'ORDER_TAX_AMOUNT'

UNION ALL
SELECT 'SCHEMA_CHECK: STG_MENU has IS_DAIRY_FREE_FLAG',
       IFF(COUNT(*) = 1, 'PASS', 'FAIL'),
       IFF(COUNT(*) = 1, 'Column exists', 'Column NOT found — JSON not flattened')
FROM TASTYBYTES_REFINED.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'STAGING' AND TABLE_NAME = 'STG_MENU' AND COLUMN_NAME = 'IS_DAIRY_FREE_FLAG'

UNION ALL
SELECT 'SCHEMA_CHECK: STG_MENU has _LOAD_TS metadata',
       IFF(COUNT(*) = 1, 'PASS', 'FAIL'),
       IFF(COUNT(*) = 1, 'Metadata column exists', 'Metadata column NOT found')
FROM TASTYBYTES_REFINED.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'STAGING' AND TABLE_NAME = 'STG_MENU' AND COLUMN_NAME = '_LOAD_TS'

UNION ALL
SELECT 'SCHEMA_CHECK: DIM_MENU has SCD2 columns',
       IFF(COUNT(*) = 3, 'PASS', 'FAIL'),
       'Found ' || COUNT(*) || ' of 3 SCD2 columns (VALID_FROM, VALID_TO, IS_CURRENT)'
FROM TASTYBYTES_CONSUMPTION.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'WAREHOUSE' AND TABLE_NAME = 'DIM_MENU'
  AND COLUMN_NAME IN ('VALID_FROM', 'VALID_TO', 'IS_CURRENT')

UNION ALL
SELECT 'SCHEMA_CHECK: DIM_MENU has DIM_MENU_SK',
       IFF(COUNT(*) = 1, 'PASS', 'FAIL'),
       IFF(COUNT(*) = 1, 'Surrogate key exists', 'Surrogate key NOT found')
FROM TASTYBYTES_CONSUMPTION.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'WAREHOUSE' AND TABLE_NAME = 'DIM_MENU' AND COLUMN_NAME = 'DIM_MENU_SK'

UNION ALL
SELECT 'SCHEMA_CHECK: FACT_ORDER_LINE has all SK columns',
       IFF(COUNT(*) = 4, 'PASS', 'FAIL'),
       'Found ' || COUNT(*) || ' of 4 SK columns'
FROM TASTYBYTES_CONSUMPTION.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'WAREHOUSE' AND TABLE_NAME = 'FACT_ORDER_LINE'
  AND COLUMN_NAME IN ('DIM_MENU_SK', 'DIM_CUSTOMER_SK', 'DIM_LOCATION_SK', 'DIM_DATE_SK')

-- =====================================================================
-- SECTION 3: Data Checks
-- =====================================================================

UNION ALL
SELECT 'DATA_CHECK: STG_MENU row count',
       IFF(cnt = 100, 'PASS', 'FAIL'),
       'Row count: ' || cnt
FROM (SELECT COUNT(*) AS cnt FROM TASTYBYTES_REFINED.STAGING.STG_MENU)

UNION ALL
SELECT 'DATA_CHECK: STG_CUSTOMER_LOYALTY row count',
       IFF(cnt = 222540, 'PASS', 'FAIL'),
       'Row count: ' || cnt
FROM (SELECT COUNT(*) AS cnt FROM TASTYBYTES_REFINED.STAGING.STG_CUSTOMER_LOYALTY)

UNION ALL
SELECT 'DATA_CHECK: DIM_MENU current records',
       IFF(cnt = 100, 'PASS', 'FAIL'),
       'Current records: ' || cnt || ' (expected 100)'
FROM (SELECT COUNT(*) AS cnt FROM TASTYBYTES_CONSUMPTION.WAREHOUSE.DIM_MENU WHERE IS_CURRENT = TRUE)

UNION ALL
SELECT 'DATA_CHECK: DIM_CUSTOMER row count',
       IFF(cnt = 222540, 'PASS', 'FAIL'),
       'Row count: ' || cnt
FROM (SELECT COUNT(*) AS cnt FROM TASTYBYTES_CONSUMPTION.WAREHOUSE.DIM_CUSTOMER WHERE IS_DELETED = FALSE)

UNION ALL
SELECT 'DATA_CHECK: FACT null DIM_MENU_SK',
       IFF(cnt = 0, 'PASS', 'FAIL'),
       'NULL DIM_MENU_SK count: ' || cnt
FROM (SELECT COUNT_IF(DIM_MENU_SK IS NULL) AS cnt FROM TASTYBYTES_CONSUMPTION.WAREHOUSE.FACT_ORDER_LINE)

UNION ALL
SELECT 'DATA_CHECK: FACT null DIM_CUSTOMER_SK',
       IFF(cnt = 0, 'PASS', 'FAIL'),
       'NULL DIM_CUSTOMER_SK count: ' || cnt
FROM (SELECT COUNT_IF(DIM_CUSTOMER_SK IS NULL) AS cnt FROM TASTYBYTES_CONSUMPTION.WAREHOUSE.FACT_ORDER_LINE)

UNION ALL
SELECT 'DATA_CHECK: FACT null DIM_LOCATION_SK',
       IFF(cnt = 0, 'PASS', 'FAIL'),
       'NULL DIM_LOCATION_SK count: ' || cnt
FROM (SELECT COUNT_IF(DIM_LOCATION_SK IS NULL) AS cnt FROM TASTYBYTES_CONSUMPTION.WAREHOUSE.FACT_ORDER_LINE)

UNION ALL
SELECT 'DATA_CHECK: FACT null DIM_DATE_SK',
       IFF(cnt = 0, 'PASS', 'FAIL'),
       'NULL DIM_DATE_SK count: ' || cnt
FROM (SELECT COUNT_IF(DIM_DATE_SK IS NULL) AS cnt FROM TASTYBYTES_CONSUMPTION.WAREHOUSE.FACT_ORDER_LINE)

UNION ALL
SELECT 'DATA_CHECK: RPT view returns 12 months',
       IFF(cnt = 12, 'PASS', 'FAIL'),
       'Distinct months: ' || cnt
FROM (SELECT COUNT(DISTINCT MONTH_START_DATE) AS cnt FROM TASTYBYTES_CONSUMPTION.ANALYTICS.RPT_MONTHLY_MENU_SALES WHERE YEAR = 2022)

UNION ALL
SELECT 'DATA_CHECK: Revenue tie-back',
       IFF(ABS(view_rev - fact_rev) < 0.01, 'PASS', 'FAIL'),
       'View revenue: ' || view_rev || ', Fact revenue: ' || fact_rev
FROM (
  SELECT
    (SELECT SUM(TOTAL_REVENUE) FROM TASTYBYTES_CONSUMPTION.ANALYTICS.RPT_MONTHLY_MENU_SALES) AS view_rev,
    (SELECT SUM(LINE_PRICE) FROM TASTYBYTES_CONSUMPTION.WAREHOUSE.FACT_ORDER_LINE) AS fact_rev
)

-- =====================================================================
-- SECTION 4: Governance Checks
-- =====================================================================

UNION ALL
SELECT 'GOV_CHECK: STG_MENU has table comment',
       IFF(LENGTH(COMMENT) > 0, 'PASS', 'FAIL'),
       IFF(LENGTH(COMMENT) > 0, 'Comment: ' || LEFT(COMMENT, 80), 'No comment set')
FROM TASTYBYTES_REFINED.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'STAGING' AND TABLE_NAME = 'STG_MENU'

UNION ALL
SELECT 'GOV_CHECK: STG_ORDER_HEADER has table comment',
       IFF(LENGTH(COMMENT) > 0, 'PASS', 'FAIL'),
       IFF(LENGTH(COMMENT) > 0, 'Comment: ' || LEFT(COMMENT, 80), 'No comment set')
FROM TASTYBYTES_REFINED.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'STAGING' AND TABLE_NAME = 'STG_ORDER_HEADER'

UNION ALL
SELECT 'GOV_CHECK: DIM_MENU has table comment',
       IFF(LENGTH(COMMENT) > 0, 'PASS', 'FAIL'),
       IFF(LENGTH(COMMENT) > 0, 'Comment: ' || LEFT(COMMENT, 80), 'No comment set')
FROM TASTYBYTES_CONSUMPTION.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'WAREHOUSE' AND TABLE_NAME = 'DIM_MENU'

UNION ALL
SELECT 'GOV_CHECK: RPT view has table comment',
       IFF(LENGTH(COMMENT) > 0, 'PASS', 'FAIL'),
       IFF(LENGTH(COMMENT) > 0, 'Comment: ' || LEFT(COMMENT, 80), 'No comment set')
FROM TASTYBYTES_CONSUMPTION.INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'ANALYTICS' AND TABLE_NAME = 'RPT_MONTHLY_MENU_SALES'

-- =====================================================================
-- SECTION 5: Tag Checks (requires TB_ADMIN or appropriate privileges)
-- Uses TAG_REFERENCES to verify tags were applied
-- =====================================================================

UNION ALL
SELECT 'TAG_CHECK: STG_MENU DATA_DOMAIN tag',
       IFF(COUNT(*) > 0, 'PASS', 'FAIL'),
       IFF(COUNT(*) > 0, 'Tag applied', 'DATA_DOMAIN tag NOT found')
FROM TABLE(TASTYBYTES_REFINED.INFORMATION_SCHEMA.TAG_REFERENCES(
  'TASTYBYTES_REFINED.STAGING.STG_MENU', 'TABLE'))
WHERE TAG_NAME = 'DATA_DOMAIN'

UNION ALL
SELECT 'TAG_CHECK: STG_CUSTOMER_LOYALTY TASTY_PII on FIRST_NAME',
       IFF(COUNT(*) > 0, 'PASS', 'FAIL'),
       IFF(COUNT(*) > 0, 'PII tag applied', 'TASTY_PII tag NOT found on FIRST_NAME')
FROM TABLE(TASTYBYTES_REFINED.INFORMATION_SCHEMA.TAG_REFERENCES(
  'TASTYBYTES_REFINED.STAGING.STG_CUSTOMER_LOYALTY', 'TABLE'))
WHERE TAG_NAME = 'TASTY_PII' AND COLUMN_NAME = 'FIRST_NAME'

UNION ALL
SELECT 'TAG_CHECK: DIM_CUSTOMER TASTY_PII on E_MAIL',
       IFF(COUNT(*) > 0, 'PASS', 'FAIL'),
       IFF(COUNT(*) > 0, 'PII tag applied', 'TASTY_PII tag NOT found on E_MAIL')
FROM TABLE(TASTYBYTES_CONSUMPTION.INFORMATION_SCHEMA.TAG_REFERENCES(
  'TASTYBYTES_CONSUMPTION.WAREHOUSE.DIM_CUSTOMER', 'TABLE'))
WHERE TAG_NAME = 'TASTY_PII' AND COLUMN_NAME = 'E_MAIL'

-- =====================================================================
-- SECTION 6: Procedure and Task Existence
-- =====================================================================

UNION ALL
SELECT 'PROC_EXISTS: SP_LOAD_STG_MENU',
       IFF(COUNT(*) >= 1, 'PASS', 'FAIL'),
       IFF(COUNT(*) >= 1, 'Procedure exists', 'Procedure NOT found')
FROM TASTYBYTES_REFINED.INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = 'STAGING' AND PROCEDURE_NAME = 'SP_LOAD_STG_MENU'

UNION ALL
SELECT 'PROC_EXISTS: SP_LOAD_STG_ORDER_HEADER',
       IFF(COUNT(*) >= 1, 'PASS', 'FAIL'),
       IFF(COUNT(*) >= 1, 'Procedure exists', 'Procedure NOT found')
FROM TASTYBYTES_REFINED.INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = 'STAGING' AND PROCEDURE_NAME = 'SP_LOAD_STG_ORDER_HEADER'

UNION ALL
SELECT 'PROC_EXISTS: SP_LOAD_STG_ORDER_DETAIL',
       IFF(COUNT(*) >= 1, 'PASS', 'FAIL'),
       IFF(COUNT(*) >= 1, 'Procedure exists', 'Procedure NOT found')
FROM TASTYBYTES_REFINED.INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = 'STAGING' AND PROCEDURE_NAME = 'SP_LOAD_STG_ORDER_DETAIL'

UNION ALL
SELECT 'PROC_EXISTS: SP_LOAD_STG_CUSTOMER_LOYALTY',
       IFF(COUNT(*) >= 1, 'PASS', 'FAIL'),
       IFF(COUNT(*) >= 1, 'Procedure exists', 'Procedure NOT found')
FROM TASTYBYTES_REFINED.INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = 'STAGING' AND PROCEDURE_NAME = 'SP_LOAD_STG_CUSTOMER_LOYALTY'

UNION ALL
SELECT 'PROC_EXISTS: SP_LOAD_DIM_MENU',
       IFF(COUNT(*) >= 1, 'PASS', 'FAIL'),
       IFF(COUNT(*) >= 1, 'Procedure exists', 'Procedure NOT found')
FROM TASTYBYTES_CONSUMPTION.INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = 'WAREHOUSE' AND PROCEDURE_NAME = 'SP_LOAD_DIM_MENU'

UNION ALL
SELECT 'PROC_EXISTS: SP_LOAD_DIM_CUSTOMER',
       IFF(COUNT(*) >= 1, 'PASS', 'FAIL'),
       IFF(COUNT(*) >= 1, 'Procedure exists', 'Procedure NOT found')
FROM TASTYBYTES_CONSUMPTION.INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = 'WAREHOUSE' AND PROCEDURE_NAME = 'SP_LOAD_DIM_CUSTOMER'

UNION ALL
SELECT 'PROC_EXISTS: SP_LOAD_FACT_ORDER_LINE',
       IFF(COUNT(*) >= 1, 'PASS', 'FAIL'),
       IFF(COUNT(*) >= 1, 'Procedure exists', 'Procedure NOT found')
FROM TASTYBYTES_CONSUMPTION.INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = 'WAREHOUSE' AND PROCEDURE_NAME = 'SP_LOAD_FACT_ORDER_LINE'

-- =====================================================================
-- SECTION 7: Masking Check (switch to TB_ANALYST to verify PII is masked)
-- =====================================================================

UNION ALL
SELECT 'MASKING_CHECK: STG_CUSTOMER_LOYALTY.FIRST_NAME masked for analyst',
       IFF(val = '**MASKED**', 'PASS', 'FAIL'),
       'Value seen by TB_ANALYST: ' || val
FROM (
  SELECT FIRST_NAME AS val
  FROM TASTYBYTES_REFINED.STAGING.STG_CUSTOMER_LOYALTY
  LIMIT 1
)

ORDER BY CHECK_NAME;
